apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium-agent
  namespace: kube-system
  labels:
    k8s-app: cilium-agent
spec:
  selector:
    matchLabels:
      k8s-app: cilium-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: cilium-agent
    spec:
      hostNetwork: true
      priorityClassName: system-node-critical
      serviceAccountName: cilium-agent
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
      - key: node-role.kubernetes.io/controller
        operator: Exists
      - key: node.kubernetes.io/not-ready
        operator: Exists
      %{~ for key in daemonset_tolerations ~}
      - key: ${key}
        operator: Exists
      %{~ endfor ~}
      initContainers:
      # Required to mount cgroup2 filesystem on the underlying Kubernetes node.
      # We use nsenter command with host's cgroup and mount namespaces enabled.
      - name: mount-cgroup
        image: ${cilium_agent_image}
        command:
          - sh
          - -c
          # The statically linked Go program binary is invoked to avoid any
          # dependency on utilities like sh and mount that can be missing on certain
          # distros installed on the underlying host. Copy the binary to the
          # same directory where we install cilium cni plugin so that exec permissions
          # are available.
          - 'cp /usr/bin/cilium-mount /hostbin/cilium-mount && nsenter --cgroup=/hostproc/1/ns/cgroup --mount=/hostproc/1/ns/mnt "$${BIN_PATH}/cilium-mount" $CGROUP_ROOT; rm /hostbin/cilium-mount'
        env:
          - name: CGROUP_ROOT
            value: /run/cilium/cgroupv2
          - name: BIN_PATH
            value: /opt/cni/bin
        securityContext:
          privileged: true
        volumeMounts:
          - name: hostproc
            mountPath: /hostproc
          - name: cni-bin-dir
            mountPath: /hostbin

      - name: clean-cilium-state
        image: ${cilium_agent_image}
        command:
        - /init-container.sh
        env:
        - name: CILIUM_WAIT_BPF_MOUNT
          valueFrom:
            configMapKeyRef:
              name: cilium
              key: wait-bpf-mount
              optional: true
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
          mountPropagation: HostToContainer
        - name: var-run-cilium
          mountPath: /var/run/cilium
        # Required to mount cgroup filesystem from the host to cilium agent pod
        - name: cilium-cgroup
          mountPath: /run/cilium/cgroupv2
          mountPropagation: HostToContainer

      containers:
      - name: cilium-agent
        image: ${cilium_agent_image}
        command:
        - cilium-agent
        args:
        - --config-dir=/tmp/cilium/config-map
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        ports:
          # Not yet used, prefer exec's
          - name: health
            protocol: TCP
            containerPort: 9876
        lifecycle:
          # Install Cilium CNI binary and CNI network config
          postStart:
            exec:
              command:
              - "/cni-install.sh"
              - "--enable-debug=false"
              - "--cni-exclusive=true"
          preStop:
            exec:
              command:
              - /cni-uninstall.sh
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        livenessProbe:
          exec:
            command:
            - cilium
            - status
            - --brief
          periodSeconds: 30
          initialDelaySeconds: 120
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - cilium
            - status
            - --brief
          periodSeconds: 20
          initialDelaySeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        volumeMounts:
        # Load kernel modules
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: xtables-lock
          mountPath: /run/xtables.lock
        # Keep state between restarts
        - name: var-run-cilium
          mountPath: /var/run/cilium
        - name: sys-fs-bpf
          mountPath: /sys/fs/bpf
        # Configuration
        - name: config
          mountPath: /tmp/cilium/config-map
          readOnly: true
        # Install CNI plugin and config on host
        - name: cni-bin-dir
          mountPath: /host/opt/cni/bin
        - name: cni-conf-dir
          mountPath: /host/etc/cni/net.d
      terminationGracePeriodSeconds: 1
      volumes:
      # Load kernel modules
      - name: lib-modules
        hostPath:
          path: /lib/modules
      # Access iptables concurrently with other processes (e.g. kube-proxy)
      - name: xtables-lock
        hostPath:
          type: FileOrCreate
          path: /run/xtables.lock
      # Keep state between restarts
      - name: var-run-cilium
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
      # Keep state between restarts for bpf maps
      - name: sys-fs-bpf
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      # Mount host cgroup2 filesystem
      - name: hostproc
        hostPath:
          path: /proc
          type: Directory
      - name: cilium-cgroup
        hostPath:
          path: /run/cilium/cgroupv2
          type: DirectoryOrCreate
      # Read configuration
      - name: config
        configMap:
          name: cilium
      # Install CNI plugin and config on host
      - name: cni-bin-dir
        hostPath:
          type: DirectoryOrCreate
          path:  /opt/cni/bin
      - name: cni-conf-dir
        hostPath:
          type: DirectoryOrCreate
          path: /etc/cni/net.d

